### ISSUE TITLE
日志问题

### ISSUE THREAD

**Issue by AlphatoBeta** [iiijam/alisthelper#1]
**问题1**
启动日志：
INFO[2023-05-04 10:41:47] success load storage: [/闃块噷浜戠洏OPEN], driver: [AliyundriveOpen] 
INFO[2023-05-04 10:41:47] success load storage: [/123浜戠洏], driver: [123Pan] 
情况说明：
/闃块噷浜戠洏OPEN，应该是阿里云盘OPEN，
/123浜戠洏，应该是123云盘
推测是字符编码的问题，不影响使用，只是怪怪的。

**问题2**
点击软件界面Admin，显示日志：
INFO[2023-05-04 10:47:30] admin user's info: 
username: admin
password: LrazTsln 
此条日志只能全部复制，不能单独复制密码，希望可以优化日志的选择和复制，方便单独复制密码

**Comment by iiijam** [comment]
请问你的终端设置的是什么格式的输出编码

**Comment by AlphatoBeta** [comment]
> 请问你的终端设置的是什么格式的输出编码

Windows11系统，控制面板区域设置里：非Unicode程序中所使用的当前语言：中文（简体，中国）

**Comment by iiijam** [comment]
这个应该是gbk编码的问题

**Comment by iiijam** [comment]
这些问题均在v0.0.2中修复 https://github.com/iiijam/alisthelper/releases/tag/v0.0.2
