### ISSUE TITLE
工作目录找不到 alist.exe

### ISSUE THREAD

**Issue by Hunlongyu** [iiijam/alisthelper#4]
![image](https://user-images.githubusercontent.com/15273630/237058319-f8ad9edc-9593-4325-a6cf-3af526fb873a.png)
如图，我把 alist.exe 放到 alisthelper.exe 同级目录下，且没有中文路径，win11 系统。
![image](https://user-images.githubusercontent.com/15273630/237058597-35b16aa1-9d60-4946-9c9e-3f8989f26b7a.png)
中间选择了语言，切换了主题颜色，识别失败后，重启过软件。

**Comment by Hunlongyu** [comment]
![image](https://user-images.githubusercontent.com/15273630/237059528-9b81c05d-fe77-42b6-9a05-161c24d84ac7.png)
好吧，是提示有问题，实际上已经找到了。
![image](https://user-images.githubusercontent.com/15273630/237059690-74378613-d26c-4dcb-a2e8-7cf4431c4f9f.png)
修复提示文字就好了

**Comment by iiijam** [comment]
可否复现该步骤？
另外，不推荐直接将alist二进制文件直接放在同一目录下；因为可能会导致data文件夹的冲突，最好单独为alist建立一个文件夹。

**Comment by Hunlongyu** [comment]
好像是我乌龙了，把 “找到” 看成 “没找到”。软件很棒，给你点赞。

**Comment by hjy-os** [comment]
把安装目录里的alisthelper.exe改为alist.exe
